"use strict";
const DEFAULT_SETTINGS = {
  activeTheme: "Lime",
  customThemes: [],
  windowOpacity: 1,
  fontSizeOffset: 0,
  showHidden: false,
  showSystem: false,
  foldersFirst: true,
  previewVisible: true,
  sidebarVisible: true,
  confirmDelete: true,
  deleteToTrash: true,
  showFolderSizes: true,
  showGitStatus: true,
  terminalVisible: false,
  terminalHeight: 240,
  shell: "",
  assistantUrl: "ws://127.0.0.1:8765/ws",
  assistantToken: "",
  pinned: [],
  recentFiles: [],
  recentFolders: []
};
function mediaUrl(absolutePath) {
  return `onyx-media://f/?p=${encodeURIComponent(absolutePath)}`;
}
const CH = {
  readDir: "fs:readDir",
  drives: "fs:drives",
  homeDir: "fs:homeDir",
  knownFolders: "fs:knownFolders",
  resolvePath: "fs:resolvePath",
  parentOf: "fs:parentOf",
  watch: "fs:watch",
  unwatch: "fs:unwatch",
  fsEvent: "fs:event",
  open: "op:open",
  reveal: "op:reveal",
  openTerminal: "op:openTerminal",
  conflicts: "op:conflicts",
  copy: "op:copy",
  move: "op:move",
  rename: "op:rename",
  renameMany: "op:renameMany",
  remove: "op:remove",
  mkdir: "op:mkdir",
  newFile: "op:newFile",
  undo: "op:undo",
  undoLabel: "op:undoLabel",
  opProgress: "op:progress",
  clipCopy: "clip:copy",
  clipCut: "clip:cut",
  clipRead: "clip:read",
  copyText: "clip:copyText",
  preview: "an:preview",
  fileIcons: "an:fileIcons",
  folderSize: "an:folderSize",
  gitStatus: "an:gitStatus",
  search: "an:search",
  cancelSearch: "an:cancelSearch",
  searchHit: "an:searchHit",
  searchDone: "an:searchDone",
  startDrag: "dnd:start",
  loadSettings: "app:loadSettings",
  saveSettings: "app:saveSettings",
  pickFolder: "app:pickFolder",
  windowControl: "app:windowControl",
  setOpacity: "app:setOpacity",
  windowState: "app:windowState",
  appVersion: "app:version",
  ptyStart: "pty:start",
  ptyWrite: "pty:write",
  ptyResize: "pty:resize",
  ptyKill: "pty:kill",
  ptySetCwd: "pty:setCwd",
  ptyData: "pty:data",
  ptyExit: "pty:exit",
  ptyCwd: "pty:cwd",
  checkForUpdate: "app:checkForUpdate",
  updateStatus: "app:updateStatus",
  restartToUpdate: "app:restartToUpdate"
};
exports.CH = CH;
exports.DEFAULT_SETTINGS = DEFAULT_SETTINGS;
exports.mediaUrl = mediaUrl;
